#!/bin/bash

filename=sync-packagelist
now="$(date +'-%d-%m-%Y_%H:%M:%S')"
directory=$(cd `dirname $0` && pwd)

echo "Welcome, do you want to see your upgradeable packages? - confirm with 'y' "
read exe
if [ "$exe" = n ]; then
	exit 0
fi

echo "pacman pulls new updates from remote"
sudo pacman -Sy
cd $directory/Logs

if [ ! -f $filename$now ]; then
	touch $filename$now
	echo "$filename$now in $directory/Logs created" 
else
	echo "Error"
fi

echo "Log generated $now" > $filename$now
echo "Packagename CurrentVersion -> UpgradeVersion" > $filename$now
echo "--------------------------------------" >> $filename$now
sudo pacman -Qu >> $filename$now


